build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

# deploy:
#   stage: deploy
#   image:
#     name: 
#   script:
#     - mkdir ~/.kube
#     - echo $kube_config | base64 -d > ~/.kube/config
#     - kubectl apply -f ohmyform-deployment.yaml
#     - kubectl rollout restart deployment ohmyform-depl
