stages:
  - build
  - deploy
build:
  stage: build
  image: docker:latest
  services:
  - name: docker:dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker pull jtp03a/jpeterson-dev:latest || true
    - docker build --cache-from jtp03a/jpeterson-dev:latest --tag jtp03a/jpeterson-dev:latest .
    - docker push jtp03a/jpeterson-dev:latest
deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials jp-ap-cluster-1 --zone=us-central1
    - echo $MONGODB_CONN > dbconn.txt
    - echo $JWT_SECRET > jwtsecret.txt
    - echo $PEXE_KEY > pexelkey.txt
    - kubectl create secret generic mongodb-secrets --from-file=mongodb_conn=./dbconn.txt
    - kubectl create secret generic jwt-secrets --from-file=jwt_secret=./jwtsecret.txt
    - kubectl create secret generic pexel-secrets --from-file=pexel_key=./pexelkey.txt
    - kubectl apply -f service.yaml
    - kubectl apply -f jpeterson-dev-deploy.yaml