apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpeterson-dev
  labels:
    app: jpeterson-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpeterson-dev
  template:
    metadata:
      labels:
        app: jpeterson-dev
    spec:
      containers:
      - name: jpeterson-dev
        image: registry.gitlab.com/jtp03a/jpeterson-dev
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb_conn
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: jwt_secret
        - name: PEXELKEY
          valueFrom:
            secretKeyRef:
              name: pexel-secrets
              key: pexel_key
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: jpdev-svc
spec:
  selector:
    app: jpeterson-dev
  ports:
    - protocol: TCP
      port: 4000  
      targetPort: 4000
